export const OPTIMIZATION_STATE_NEW = 0;
export const OPTIMIZATION_STATE_STARTED = 1;
export const OPTIMIZATION_STATE_CALCULATING = 2;
export const OPTIMIZATION_STATE_FINISHED = 3;
export const OPTIMIZATION_STATE_CANCELLING = 10;
export const OPTIMIZATION_STATE_CANCELLED = 11;


