export const OPTIMIZATION_STATE_NEW = 0;
export const OPTIMIZATION_STATE_STARTED = 1;
export const OPTIMIZATION_STATE_PREPROCESSING = 2;
export const OPTIMIZATION_STATE_PREPROCESSING_FINISHED = 3;
export const OPTIMIZATION_STATE_QUEUED = 4;
export const OPTIMIZATION_STATE_CALCULATING = 5;
export const OPTIMIZATION_STATE_FINISHED = 3;

export const OPTIMIZATION_STATE_CANCELLING = 11;
export const OPTIMIZATION_STATE_CANCELLED = 12;

export const OPTIMIZATION_STATE_ERROR_RECALCULATING_MODEL = 40;
export const OPTIMIZATION_STATE_ERROR_PUBLISHING = 41;
export const OPTIMIZATION_STATE_ERROR_OPTIMIZATION_CORE = 42;
