export const getInitialState = () => {
    return {
        selected: '',
        packages: {
            flow: {
                availablePackages: [],
            },
            solver: {
                availablePackages: [],
            },
        },
        lpf: {
            hdry: 0.0,
            wetfct: 0.0,
            iwetit: 0.0,
            ihdwet: 0.0,
            vkcb: 0.0,
            wetdry: 0.0,
            storagecoefficient: false,
            constantcv: false,
            nocvcorrection: false,
            novfc: false,
        },
        upw: {
            hdry: 0.0,
            iphdry: 0.0,
            vkcb: 0.0,
        },
        pcg: {
            mxiter: 0,
            iter1: 0,
            npcond: 0,
            hclose: 0.0,
            rclose: 0.0,
            relax: 0.0,
            nbpol: 0,
            iprpcg: 0,
            mutpcg: 0,
            damp: 0.0,
            dampt: 0.0,
            ihcofadd: 0,
        },
        nwt: {
            headtol: 0.0,
            fluxtol: 0.0,
            maxiterout: 0,
            thickfact: 0.0,
            linmeth: 0,
            iprnwt: 0,
            ibotavg: 0,
            options: '',
            continue: true,
            dbdtheta: 0.0,
            dbdkappa: 0.0,
            dbdgamma: 0.0,
            momfact: 0.0,
            backflag: 0,
            maxbackiter: 0,
            backtol: 0.0,
            backreduce: 0.0,
            maxitinner: 0,
            ilumethod: 0,
            levfill: 0,
            stoptol: 0.0,
            msdr: 0,
            iacl: 0,
            norder: 0,
            level: 0,
            north: 0,
            iredsys: 0,
            rrctols: 0.0,
            idroptol: 0,
            epsrn: 0.0,
            hclosexmd: 0.0,
            mxiterxmd: 0,
        },
    };
};
